""

load("//BazelUtilities/solutions:solutions.bzl", "solution_project_build")
load(":project.bzl", "info_Sandbox")

solution_project_build(
    info = info_Sandbox,
    srcs = [ "src/Sandbox/Sandbox.cpp" ]
)
